# Generated by Django 5.1.6 on 2025-02-14 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_appointment_delete_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appt_scheduled_by',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='customize_date',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='location_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='main_appt',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='mrn',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='phressia_filter',
            field=models.CharField(max_length=50),
        ),
    ]
